### ISSUE TITLE
Biasing window bug

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#119]
Any time when you attempt to add another word to the list and adjust values, every other already present settings will just auto-delete themselves for no reason. New UI Janeway.

**Comment by ebolam** [comment]
Was there any errors in the console (colab text or if local the command prompt)? I can't get it to break for me.

**Comment by MrXen0morph** [comment]
Not sure if the response reached you (I guess replying directly via gmail doesn't work as intended...), so here's the copy paste of my response from there.

Weirdly enough, no, nothing at all, aside from autosave kicking in after the disappears bug. Try to drag sliders outside of their "boxes", this often resulted in such behavior. Everything but the newly added line vanish.

**Comment by scythe000** [comment]
Working ok for me, I just tested it.

**Comment by MrXen0morph** [comment]
Weirdly enough, no, nothing at all, aside from autosave kicking in after
the disappears bug. Try to drag sliders outside of their "boxes", this
often resulted in such behavior. Everything but the newly added line
vanish.

ср, 14 вер. 2022 р., 19:17 користувач ebolam ***@***.***>
пише:
