### ISSUE TITLE
AttributeError: module 'transformers.utils.hub' has no attribute 'BinaryIO'

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#130]
Launching KoboldAI with the following options : python3 aiserver.py --model KoboldAI/fairseq-dense-13B-Janeway --colab
Initializing Flask... Colab Check: True
OK!

Starting webserver...
Welcome to KoboldAI!
You have selected the following Model: KoboldAI/fairseq-dense-13B-Janeway
Traceback (most recent call last):
  File "aiserver.py", line 10640, in <module>
    patch_transformers()
  File "aiserver.py", line 1528, in patch_transformers
    patch_transformers_download()
  File "aiserver.py", line 1447, in patch_transformers_download
    file_name: transformers.utils.hub.Optional[str] = None,
AttributeError: module 'transformers.utils.hub' has no attribute 'BinaryIO'

**Comment by MrXen0morph** [comment]
Error seems to be present both on the new UI link and United, however, trying to start Official seems to work. As a weird bonus, after Official branch updates the transformer file(?), restarting on new UI/United makes the whole thing work again.

**Comment by LightSaveUs** [comment]
> Error seems to be present both on the new UI link and United, however, trying to start Official seems to work. As a weird bonus, after Official branch updates the transformer file(?), restarting on new UI/United makes the whole thing work again.

Yes, we know about most of the errors you've sent. We were already discussing their fixing last night.

**Comment by ebolam** [comment]
This one is an error in all versions. The solution was to temporarily cap transformers to a previous version. That should be in my git now.

**Comment by MrXen0morph** [comment]
Lovely, just trying to do my part as a common user of the platform.
Official version is too AID-like when it comes to understanding topics,
(but still marginally better than the AID itself), and the one behind the
new ui is way better at that. Therefore, I simply cannot go back to
Official anymore, leaving me the only option is to use new UI xd. The
sooner all the bugs are discovered, the better.

чт, 15 вер. 2022 р., 22:20 користувач LightSaveUs ***@***.***>
пише:
