### ISSUE TITLE
Typing in WI Finder adds spaces around occurances in game text

### ISSUE THREAD

**Issue by one-some** [ebolam/KoboldAI#136]
When searching for WI entries in the finder, the italic occurrences of that WI entry in the game text will have spaces added around them. Why? Who knows? It doesn't make much sense, but maybe theres a global onkeydown somewhere

**Comment by ebolam** [comment]
Very odd. I replaced one chunk of WI entry matching code that might have helped. I need to take some time and troubleshoot both the WI highlighting and general editing as the new edit method is still a bit wonky.

**Comment by one-some** [comment]
This issue seems to be very sensitive to reproduce, so here are some instructions I've found reproduce it:
* Restart KAI
* Load test prompt
* `ctrl-k`, `>`
* type "ma"; spaces start changing here between "You are" and "Major"
* backspace and type "a" once more, this creates spaces infinity
