### ISSUE TITLE
General weirdness with editor

### ISSUE THREAD

**Issue by one-some** [ebolam/KoboldAI#140]
Noticing some strange occurrences with the editor:
- Pressing right arrow at the end of the text unfocuses the text
- Editor doesn't save text completely sometimes. I don't know how exactly to reproduce this; I'll update this issue later when I figure out how.

**Comment by ebolam** [comment]
I fixed a bug in the world info matcher that MIGHT have fixed this. I can't get the right arrow at the end of text to unfocus anymore...

The text editing I'm sure still has bugs though.
