### ISSUE TITLE
User's input/edits are completely ignored. Trying to use the generated text (with redo) doesn't work.

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#146]
Basically what the title says. 

Trying to edit the existing text doesn't get recognized by the AI (no text flashing in green, AI has the original line without any edits as primary no matter what).
Second thing is related to the retrying the inputs/outputs. AI will show the newly generated text, but trying to select it results in a very first text block appearing in place instead.

**Comment by ebolam** [comment]
Looks like we had a bug related to another fix. I believe this is corrected now. I was able to start from the sample story, edit text. Submit, Edit text, redo, edit text, etc.

**Comment by MrXen0morph** [comment]
It sort of did get fixed, but not entirely. If you just edit the line and don't do anything after that (except commiting the change by selecting something else that is), it doesn't aknowledge the change, but if you try editing another line, or just 'highlight' it, then it seems to trigger the new edit after a couple of tries.
Perhaps making a video would be a better option to explain those bugs, although I'm not sure which program to use for github... Have any suggestions perhaps?
Also I hope I don't look like an annoying f- someone, because it seems like I'm being quite 'active' with reporting various bugs recently, in such a short time frame lol.

**Comment by ebolam** [comment]
No worries on being active. We're in active development, so getting these
issues brought up is good.

For video I use obs (free) and then either post the video file or convert
it to an animated gif online somewhere.
