### ISSUE TITLE
Context Menu Issues

### ISSUE THREAD

**Issue by LightSaveUs** [ebolam/KoboldAI#152]
1) When you open the context menu, for some reason the flyout menu line on the right becomes wider and the text shifts a little.

Can be shown by doing the following actions:
1) Load the sample_story
2) Click RMB (to open context menu) on the "in the dirty snow that..." words.

Before:
![1](https://user-images.githubusercontent.com/108632621/191879940-ebf66f84-3470-4c15-8060-f132d55d15cd.png)
After:
![2](https://user-images.githubusercontent.com/108632621/191879951-dcf0c227-aebe-4d08-8b39-fb2f087cd9b8.png)

2) For some reason after the initial load in a new session, the context menu goes down under the input box.

![image](https://user-images.githubusercontent.com/108632621/191880182-d270c1de-0f76-41a1-8a7d-2db36289e0ac.png)

P.S. Hope @one-some will be able to fix both of these issues.

**Comment by one-some** [comment]
Not sure whats causing the first issue, but the second was me forgetting to add the `hidden` class to the context menu initially. I should have the second fixed in a few minutes
