### ISSUE TITLE
Chat mode continues both conversation sides

### ISSUE THREAD

**Issue by scythe000** [ebolam/KoboldAI#156]
In Chat mode, we should stop returning text once we encounter "You: ". That way we can force the bot to only give it's own responses.

ebolam — Today at 2:33 PM
Seems like a stopping condition would be simpliest, and wouldn't make the AI generate just to truncate.

Tested on opt-6.7b, and also OPT-6.7B-Erebus, new UI.

**Comment by one-some** [comment]
Note that this may cut off the generation before genamt is reached. Perhaps its best to bias the user indicator tokens by negative infinity so they're never generated

**Comment by scythe000** [comment]
Confirmed issue is also in old UI, even with single line mode on.

**Comment by scythe000** [comment]
Does this mean it's been fixed?

**Comment by ebolam** [comment]
The patch referenced doesn't look likely to affect this.

The solution going around right now is to add a stopper to the pipeline to stop it when it sees your chat name + ";"

**Comment by scythe000** [comment]
> The patch referenced doesn't look likely to affect this.
> 
> The solution going around right now is to add a stopper to the pipeline to stop it when it sees your chat name + ";"

Aha! That sounds like a great idea.

**Comment by ebolam** [comment]
Stopper is complete and should be working. Feedback is welcome.
