### ISSUE TITLE
AttributeError: 'system_settings' object has no attribute 'multi_story'

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#158]
2022-09-24 00:13:01.561 | ERROR    | __main__:g:496 - An error has been caught in function 'g', process 'MainProcess' (695), thread 'MainThread' (139955584546688):
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/thread.py", line 43, in __thread_body
    func(*args, **kwargs)
    │     │       └ {}
    │     └ ()
    └ <bound method Thread._bootstrap of <Thread(Thread-17, started daemon 139951426309392)>>

  File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function start_new_thread.<locals>.wrap_bootstrap_inner at 0x7f48f75c2a70>
    └ <Thread(Thread-17, started daemon 139951426309392)>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/thread.py", line 64, in wrap_bootstrap_inner
    bootstrap_inner()
    └ <bound method Thread._bootstrap_inner of <Thread(Thread-17, started daemon 139951426309392)>>

  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f49ee51a950>
    └ <Thread(Thread-17, started daemon 139951426309392)>
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-17, started daemon 139951426309392)>
    │    │        │    └ (<socketio.server.Server object at 0x7f49874a4950>, 'DW3GyBU-EcAp-mPcAAAB', 'PoDy5IddkaFhn38rAAAA', ['load_story', '/content/...
    │    │        └ <Thread(Thread-17, started daemon 139951426309392)>
    │    └ <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7f49874a4950>>
    └ <Thread(Thread-17, started daemon 139951426309392)>

  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
        │      │              │        │          │     └ ['load_story', '/content/KoboldAI-Client/stories/STORYNAMES_v2.json']
        │      │              │        │          └ 'DW3GyBU-EcAp-mPcAAAB'
        │      │              │        └ '/'
        │      │              └ ['load_story', '/content/KoboldAI-Client/stories/STORYNAMES_v2.json']
        │      └ <function Server._trigger_event at 0x7f498801ea70>
        └ <socketio.server.Server object at 0x7f49874a4950>

  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
           │    │        │          │       └ ('DW3GyBU-EcAp-mPcAAAB', '/content/KoboldAI-Client/stories/STORYNAMES_v2.json')
           │    │        │          └ 'load_story'
           │    │        └ '/'
           │    └ {'/': {'OAI_Key_Update': <function get_oai_models at 0x7f49824d5dd0>, 'get_cluster_models': <function get_cluster_models at 0...
           └ <socketio.server.Server object at 0x7f49874a4950>

  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 283, in _handler
    *args)
     └ ('/content/KoboldAI-Client/stories/STORYNAMES_v2.json',)

  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 826, in _handle_event
    ret = handler(*args)
          │        └ ('/content/KoboldAI-Client/stories/STORYNAMES_v2.json',)
          └ <function UI_2_load_story at 0x7f4982506dd0>

> File "aiserver.py", line 496, in g
    return f(*a, **k)
           │  │    └ {}
           │  └ ('/content/KoboldAI-Client/stories/STORYNAMES_v2.json',)
           └ <function UI_2_load_story at 0x7f4982506b00>

  File "aiserver.py", line 7870, in UI_2_load_story
    loadRequest(file)
    │           └ '/content/KoboldAI-Client/stories/STORYNAMES_v2.json'
    └ <function loadRequest at 0x7f49824a9e60>

  File "aiserver.py", line 6627, in loadRequest
    loadJSON(js)
    │        └ {'file_version': 2, 'story_name': 'STORYNAMES', 'lastact': '\nI slowly slip into a deep, restful sleep, gently lulled by the co...
    └ <function loadJSON at 0x7f49824a9ef0>

  File "aiserver.py", line 6636, in loadJSON
    load_story_v2(json_data)
    │             └ {'file_version': 2, 'story_name': 'STORYNAMES', 'lastact': '\nI slowly slip into a deep, restful sleep, gently lulled by the co...
    └ <function load_story_v2 at 0x7f49824a7050>

  File "aiserver.py", line 6744, in load_story_v2
    koboldai_vars.load_story(session['story'], js)
    │             │          │                 └ {'file_version': 2, 'story_name': 'STORYNAMES', 'lastact': '\nI slowly slip into a deep, restful sleep, gently lulled by the co...
    │             │          └ <FileSystemSession {'_permanent': True, 'story': 'STORYNAMES', 'popup_jailed_dir': '/content/KoboldAI-Client/stories', 'popup_d...
    │             └ <function koboldai_vars.load_story at 0x7f4987813710>
    └ <koboldai_settings.koboldai_vars object at 0x7f4987436550>

  File "/content/KoboldAI-Client/koboldai_settings.py", line 104, in load_story
    if not self._system_settings.multi_story:
           │    └ <koboldai_settings.system_settings object at 0x7f49874168d0>
           └ <koboldai_settings.koboldai_vars object at 0x7f4987436550>

AttributeError: 'system_settings' object has no attribute 'multi_story'

Idk how did this even happen... Most likely because of the recent edit related bug?

**Comment by ebolam** [comment]
Fixed
