### ISSUE TITLE
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#159]
Initializing Mesh Transformer JAX, please wait...
Connecting to your Colab instance's TPU
ERROR      | __main__:<module>:11483 - An error has been caught in function '<module>', process 'Process-1' (699), thread 'MainThread' (140407625398144):
Traceback (most recent call last):

> File "aiserver.py", line 11483, in <module>
    run()
    └ <function run at 0x7fb2c1dc3c20>

  File "aiserver.py", line 11444, in run
    cloudflare = _run_cloudflared(port)
                 │                └ 5000
                 └ <function _run_cloudflared at 0x7fb2c1d77a70>

  File "/usr/local/lib/python3.7/dist-packages/flask_cloudflared.py", line 68, in _run_cloudflared
    _download_cloudflared(cloudflared_path, command)
    │                     │                 └ 'cloudflared-linux-amd64'
    │                     └ '/tmp'
    └ <function _download_cloudflared at 0x7fb2c1d77b00>

  File "/usr/local/lib/python3.7/dist-packages/flask_cloudflared.py", line 123, in _download_cloudflared
    _download_file(url)
    │              └ 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64'
    └ <function _download_file at 0x7fb2c1d77b90>

  File "/usr/local/lib/python3.7/dist-packages/flask_cloudflared.py", line 130, in _download_file
    shutil.copyfileobj(r.raw, f)
    │      │           │ │    └ <_io.BufferedWriter name='/tmp/cloudflared-linux-amd64'>
    │      │           │ └ <urllib3.response.HTTPResponse object at 0x7fb2c1cdabd0>
    │      │           └ <Response [200]>
    │      └ <function copyfileobj at 0x7fb32f081ef0>
    └ <module 'shutil' from '/usr/lib/python3.7/shutil.py'>

  File "/usr/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
          │    │    └ 16384
          │    └ <function HTTPResponse.read at 0x7fb32ffb7f80>
          └ <urllib3.response.HTTPResponse object at 0x7fb2c1cdabd0>

  File "/usr/local/lib/python3.7/dist-packages/urllib3/response.py", line 444, in read
    data = self._fp.read(amt)
           │    │   │    └ 16384
           │    │   └ <function HTTPResponse.read at 0x7fb32ffef0e0>
           │    └ <http.client.HTTPResponse object at 0x7fb2c1dae350>
           └ <urllib3.response.HTTPResponse object at 0x7fb2c1cdabd0>

  File "/usr/lib/python3.7/http/client.py", line 465, in read
    n = self.readinto(b)
        │    │        └ bytearray(b'\xe9`\x01\x00\x00A\x81\xf9#\x94z}ucL\x8d\r\xcb\xb0\xb0\x00L9\xcf\x0f\x85G\x01\x00\x00H\x8bO L\x89\xc0\xff\xd1H\x8...
        │    └ <function HTTPResponse.readinto at 0x7fb32ffef170>
        └ <http.client.HTTPResponse object at 0x7fb2c1dae350>
  File "/usr/lib/python3.7/http/client.py", line 509, in readinto
    n = self.fp.readinto(b)
        │    │           └ bytearray(b'\xe9`\x01\x00\x00A\x81\xf9#\x94z}ucL\x8d\r\xcb\xb0\xb0\x00L9\xcf\x0f\x85G\x01\x00\x00H\x8bO L\x89\xc0\xff\xd1H\x8...
        │    └ None
        └ <http.client.HTTPResponse object at 0x7fb2c1dae350>
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
           │    │               └ <memory at 0x7fb2c236d2c0>
           │    └ None
           └ <socket.SocketIO object at 0x7fb2c1cdaf10>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/ssl.py", line 253, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
           │    │          │       │                         └ <memory at 0x7fb2c236d2c0>
           │    │          │       └ 0
           │    │          └ 9280
           │    └ <function GreenSSLSocket._base_recv at 0x7fb3306f1680>
           └ <eventlet.green.ssl.GreenSSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/ssl.py", line 268, in _base_recv
    read = self.read(nbytes, buffer_)
           │    │    │       └ <memory at 0x7fb2c236d2c0>
           │    │    └ 9280
           │    └ <function GreenSSLSocket.read at 0x7fb33075c710>
           └ <eventlet.green.ssl.GreenSSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/ssl.py", line 188, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
          │               │            │       └ {}
          │               │            └ (9280, <memory at 0x7fb2c236d2c0>)
          │               └ <eventlet.green.ssl.GreenSSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
          └ <class 'eventlet.green.ssl.GreenSSLSocket'>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/ssl.py", line 162, in _call_trampolining
    return func(*a, **kw)
           │     │    └ {}
           │     └ (9280, <memory at 0x7fb2c236d2c0>)
           └ <bound method SSLSocket.read of <eventlet.green.ssl.GreenSSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketK...

  File "/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
           │    │            │    └ <memory at 0x7fb2c236d2c0>
           │    │            └ 9280
           │    └ None
           └ <eventlet.green.ssl.GreenSSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)
ERROR      | __main__:<module>:11483 - An error has been caught in function '<module>', process 'MainProcess' (690), thread 'MainThread' (140407625398144):
Traceback (most recent call last):

> File "aiserver.py", line 11483, in <module>
    run()
    └ <function run at 0x7fb2c1dc3c20>

  File "aiserver.py", line 11444, in run
    cloudflare = _run_cloudflared(port)
                 │                └ 5000
                 └ <function _run_cloudflared at 0x7fb2c1d77a70>

  File "/usr/local/lib/python3.7/dist-packages/flask_cloudflared.py", line 68, in _run_cloudflared
    _download_cloudflared(cloudflared_path, command)
    │                     │                 └ 'cloudflared-linux-amd64'
    │                     └ '/tmp'
    └ <function _download_cloudflared at 0x7fb2c1d77b00>

  File "/usr/local/lib/python3.7/dist-packages/flask_cloudflared.py", line 123, in _download_cloudflared
    _download_file(url)
    │              └ 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64'
    └ <function _download_file at 0x7fb2c1d77b90>

  File "/usr/local/lib/python3.7/dist-packages/flask_cloudflared.py", line 130, in _download_file
    shutil.copyfileobj(r.raw, f)
    │      │           │ │    └ <_io.BufferedWriter name='/tmp/cloudflared-linux-amd64'>
    │      │           │ └ <urllib3.response.HTTPResponse object at 0x7fb2c1cdabd0>
    │      │           └ <Response [200]>
    │      └ <function copyfileobj at 0x7fb32f081ef0>
    └ <module 'shutil' from '/usr/lib/python3.7/shutil.py'>

  File "/usr/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
          │    │    └ 16384
          │    └ <function HTTPResponse.read at 0x7fb32ffb7f80>
          └ <urllib3.response.HTTPResponse object at 0x7fb2c1cdabd0>

  File "/usr/local/lib/python3.7/dist-packages/urllib3/response.py", line 444, in read
    data = self._fp.read(amt)
           │    │   │    └ 16384
           │    │   └ <function HTTPResponse.read at 0x7fb32ffef0e0>
           │    └ <http.client.HTTPResponse object at 0x7fb2c1dae350>
           └ <urllib3.response.HTTPResponse object at 0x7fb2c1cdabd0>

  File "/usr/lib/python3.7/http/client.py", line 465, in read
    n = self.readinto(b)
        │    │        └ bytearray(b'\x01\xd0\x14t\xcf\x14\x01\xd0\x14$\xcf\x14\x01\xd0\x14%\xcf\x14\x01\xd0\x14$\xcf\x145\x00\xcc\x01S\xd2\x01\x1b\xd...
        │    └ <function HTTPResponse.readinto at 0x7fb32ffef170>
        └ <http.client.HTTPResponse object at 0x7fb2c1dae350>
  File "/usr/lib/python3.7/http/client.py", line 509, in readinto
    n = self.fp.readinto(b)
        │    │           └ bytearray(b'\x01\xd0\x14t\xcf\x14\x01\xd0\x14$\xcf\x14\x01\xd0\x14%\xcf\x14\x01\xd0\x14$\xcf\x145\x00\xcc\x01S\xd2\x01\x1b\xd...
        │    └ None
        └ <http.client.HTTPResponse object at 0x7fb2c1dae350>
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
           │    │               └ <memory at 0x7fb2c236d2c0>
           │    └ None
           └ <socket.SocketIO object at 0x7fb2c1cdaf10>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/ssl.py", line 253, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
           │    │          │       │                         └ <memory at 0x7fb2c236d2c0>
           │    │          │       └ 0
           │    │          └ 8192
           │    └ <function GreenSSLSocket._base_recv at 0x7fb3306f1680>
           └ <eventlet.green.ssl.GreenSSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/ssl.py", line 268, in _base_recv
    read = self.read(nbytes, buffer_)
           │    │    │       └ <memory at 0x7fb2c236d2c0>
           │    │    └ 8192
           │    └ <function GreenSSLSocket.read at 0x7fb33075c710>
           └ <eventlet.green.ssl.GreenSSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/ssl.py", line 188, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
          │               │            │       └ {}
          │               │            └ (8192, <memory at 0x7fb2c236d2c0>)
          │               └ <eventlet.green.ssl.GreenSSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
          └ <class 'eventlet.green.ssl.GreenSSLSocket'>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/ssl.py", line 162, in _call_trampolining
    return func(*a, **kw)
           │     │    └ {}
           │     └ (8192, <memory at 0x7fb2c236d2c0>)
           └ <bound method SSLSocket.read of <eventlet.green.ssl.GreenSSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketK...

  File "/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
           │    │            │    └ <memory at 0x7fb2c236d2c0>
           │    │            └ 8192
           │    └ None
           └ <eventlet.green.ssl.GreenSSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)

Was wondering if the previous error I just reported was caused by a bad TPU instance, just in case. Got another TPU, tried to start with the same link and model, this popped up.

**Comment by ebolam** [comment]
Looks like some communication error between cloudflare and google. Might have had a minor outage.
