### ISSUE TITLE
Weird visual(?) glitch/bug with AI's output.

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#168]
In short, no matter the output (as in context), the outputted line would always miss the first word/token(?).

As a rough example, the AI should output something like "This is the forest.", but instead writes " is the forest.".

**Comment by one-some** [comment]
Fixed a bug in the prompt shaver thing in #169 that might be the cause of this

**Comment by ebolam** [comment]
Closing as assumed PR 169 fixed it.
