### ISSUE TITLE
Save function stuck on saving a no longer existing story.

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#171]
I had a test story a few days ago, right as the editing bugs popped up, and probably because of those, now no matter which story I start, there is always 2 indentical in content, stories, but with the same action count. Console always saves into the 'broken' story.
Tried to start a completely fresh story at some point again, and all the presumably deleted actions 'bleed out' into the newly created one, after I attempted to refresh the webpage.

I assume something broke on my side, but I'm not sure how to resolve this issue. I've already deleted all the txt/json files of the 'cursed' story, but it just... stuck.

**Comment by ebolam** [comment]
Not sure I understand. You load a story then hit new and you have chunks of the old story in the new story?

**Comment by MrXen0morph** [comment]
> Not sure I understand. You load a story then hit new and you have chunks of the old story in the new story?

This as well. Not sure how to explain this properly really. Trying to save a completely new story with a different name always show the old one in the console, while simultaneously saving the new one. In the end, I have two identical stories saved, but with different names. The content of the broken story also seems to be cluttered up with the new ones.

**Comment by MrXen0morph** [comment]
A weird observation I've just noticed when trying to rename a broken story...

User is trying to rename files in your server outside the jail. Blocked. Jailed Dir: /content/KoboldAI-Client/stories  Requested Dir: /content/KoboldAI-Client/stories/NAME.json

Deleting this broken story won't help, it will just reappear again on the next save with the same name.

**Comment by MrXen0morph** [comment]
Also trying to open the broken story sends the console into an infinite spiral of trying to save the first story. Trying to load the broken story (after restarting the colab...) results in this:

ERROR      | __main__:g:511 - An error has been caught in function 'g', process 'MainProcess' (1459), thread 'MainThread' (140664978651008):
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/thread.py", line 43, in __thread_body
    func(*args, **kwargs)
    │     │       └ {}
    │     └ ()
    └ <bound method Thread._bootstrap of <Thread(Thread-20, started daemon 140660759737552)>>

  File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function start_new_thread.<locals>.wrap_bootstrap_inner at 0x7fee2283de60>
    └ <Thread(Thread-20, started daemon 140660759737552)>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/thread.py", line 64, in wrap_bootstrap_inner
    bootstrap_inner()
    └ <bound method Thread._bootstrap_inner of <Thread(Thread-20, started daemon 140660759737552)>>

  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fef197527a0>
    └ <Thread(Thread-20, started daemon 140660759737552)>
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-20, started daemon 140660759737552)>
    │    │        │    └ (<socketio.server.Server object at 0x7feeaf6bfb10>, 'sQSP-rd0FHYCImMtAAAB', '14rCXK0jpu34_vwgAAAA', ['load_story', '/content/...
    │    │        └ <Thread(Thread-20, started daemon 140660759737552)>
    │    └ <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7feeaf6bfb10>>
    └ <Thread(Thread-20, started daemon 140660759737552)>

  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
        │      │              │        │          │     └ ['load_story', '/content/KoboldAI-Client/stories/NAME.json']
        │      │              │        │          └ 'sQSP-rd0FHYCImMtAAAB'
        │      │              │        └ '/'
        │      │              └ ['load_story', '/content/KoboldAI-Client/stories/NAME.json']
        │      └ <function Server._trigger_event at 0x7feeb32d8200>
        └ <socketio.server.Server object at 0x7feeaf6bfb10>

  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
           │    │        │          │       └ ('sQSP-rd0FHYCImMtAAAB', '/content/KoboldAI-Client/stories/NAME.json')
           │    │        │          └ 'load_story'
           │    │        └ '/'
           │    └ {'/': {'OAI_Key_Update': <function get_oai_models at 0x7feead74db90>, 'get_cluster_models': <function get_cluster_models at 0...
           └ <socketio.server.Server object at 0x7feeaf6bfb10>

  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 283, in _handler
    *args)
     └ ('/content/KoboldAI-Client/stories/NAME.json',)

  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 826, in _handle_event
    ret = handler(*args)
          │        └ ('/content/KoboldAI-Client/stories/NAME.json',)
          └ <function UI_2_load_story at 0x7feead7663b0>

> File "aiserver.py", line 511, in g
    return f(*a, **k)
           │  │    └ {}
           │  └ ('/content/KoboldAI-Client/stories/NAME.json',)
           └ <function UI_2_load_story at 0x7feead7660e0>

  File "aiserver.py", line 8194, in UI_2_load_story
    loadRequest(file)
    │           └ '/content/KoboldAI-Client/stories/NAME.json'
    └ <function loadRequest at 0x7feead739440>

  File "aiserver.py", line 6948, in loadRequest
    loadJSON(js)
    │        └ {'gamestarted': True, 'prompt': 'starting prompt here
    └ <function loadJSON at 0x7feead7394d0>

  File "aiserver.py", line 6961, in loadJSON
    load_story_v1(json_data)
    │             └ {'gamestarted': True, 'prompt': 'starting prompt here
    └ <function load_story_v1 at 0x7feead739560>

  File "aiserver.py", line 7037, in load_story_v1
    "root" if wi.get("folder", "root") == 'root' else js['wifolders_d'][wi['folder']]['name'], wi.get("constant", False),
              │  │                                    │                 │                      │  └ <method 'get' of 'dict' objects>
              │  │                                    │                 │                      └ {'key': '', 'keysecondary': '', 'content': "world info here
              │  │                                    │                 └ {'key': '', 'keysecondary': '', 'content': "world info here
              │  │                                    └ {'gamestarted': True, 'prompt': 'starting prompt here
              │  └ <method 'get' of 'dict' objects>
              └ {'key': '', 'keysecondary': '', 'content': "world info here

KeyError: -1

And then the original story (not the broken one) loads in. No idea why colab is dublicating any new story like that, with the bugged story name for the dublicate...

**Comment by ebolam** [comment]
This is fixed now.

**Comment by MrXen0morph** [comment]
Colab still insists on saving every single story I play/start into the broken dublicate with the same name. Perhaps something broke in my files somewhere, which causes this issue?

**Comment by ebolam** [comment]
Correct. The new UI uses a new save game format so any game opened from the
original UI and saved will be saved with a new file (name_V2.json). The UI
doesn't show the _V2 part...
