### ISSUE TITLE
KeyError: 'gamestarted'

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#172]
2022-09-26 15:49:16.442 | ERROR    | __main__:g:511 - An error has been caught in function 'g', process 'MainProcess' (698), thread 'MainThread' (139839137384320):
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/thread.py", line 43, in __thread_body
    func(*args, **kwargs)
    │     │       └ {}
    │     └ ()
    └ <bound method Thread._bootstrap of <Thread(Thread-21, started daemon 139836819589072)>>

  File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function start_new_thread.<locals>.wrap_bootstrap_inner at 0x7f2dda8d6b90>
    └ <Thread(Thread-21, started daemon 139836819589072)>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/thread.py", line 64, in wrap_bootstrap_inner
    bootstrap_inner()
    └ <bound method Thread._bootstrap_inner of <Thread(Thread-21, started daemon 139836819589072)>>

  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2ed17b77a0>
    └ <Thread(Thread-21, started daemon 139836819589072)>
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-21, started daemon 139836819589072)>
    │    │        │    └ (<socketio.server.Server object at 0x7f2e67723f50>, 'xmcfR8Zf7GTms0J9AAAB', 'ZIsBP6teY6reoA8sAAAA', ['upload_file', {'filenam...
    │    │        └ <Thread(Thread-21, started daemon 139836819589072)>
    │    └ <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7f2e67723f50>>
    └ <Thread(Thread-21, started daemon 139836819589072)>

  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
        │      │              │        │          │     └ ['upload_file', {'filename': 'test_v2.json', 'data': b'{"default": {"file_version": 2, "story_name": "test", "lastact": "With...
        │      │              │        │          └ 'xmcfR8Zf7GTms0J9AAAB'
        │      │              │        └ '/'
        │      │              └ ['upload_file', {'filename': 'test_v2.json', 'data': b'{"default": {"file_version": 2, "story_name": "test", "lastact": "With...
        │      └ <function Server._trigger_event at 0x7f2e6b33d050>
        └ <socketio.server.Server object at 0x7f2e67723f50>

  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
           │    │        │          │       └ ('xmcfR8Zf7GTms0J9AAAB', {'filename': 'test_v2.json', 'data': b'{"default": {"file_version": 2, "story_name": "test", "lastac...
           │    │        │          └ 'upload_file'
           │    │        └ '/'
           │    └ {'/': {'OAI_Key_Update': <function get_oai_models at 0x7f2e657289e0>, 'get_cluster_models': <function get_cluster_models at 0...
           └ <socketio.server.Server object at 0x7f2e67723f50>

  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 283, in _handler
    *args)
     └ ({'filename': 'test_v2.json', 'data': b'{"default": {"file_version": 2, "story_name": "test", "lastact": "Within just a few m...

  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 826, in _handle_event
    ret = handler(*args)
          │        └ ({'filename': 'test_v2.json', 'data': b'{"default": {"file_version": 2, "story_name": "test", "lastact": "Within just a few m...
          └ <function upload_file at 0x7f2e657f5320>

> File "aiserver.py", line 511, in g
    return f(*a, **k)
           │  │    └ {}
           │  └ ({'filename': 'test_v2.json', 'data': b'{"default": {"file_version": 2, "story_name": "test", "lastact": "Within just a few m...
           └ <function upload_file at 0x7f2e657cbe60>

  File "aiserver.py", line 7573, in upload_file
    loadJSON(json_data)
    │        └ {'default': {'file_version': 2, 'story_name': 'test', 'lastact': "Within just a few more minutes, my whole form disappeared i...
    └ <function loadJSON at 0x7f2e657b8320>

  File "aiserver.py", line 6959, in loadJSON
    load_story_v1(json_data)
    │             └ {'default': {'file_version': 2, 'story_name': 'test', 'lastact': "Within just a few more minutes, my whole form disappeared i...
    └ <function load_story_v1 at 0x7f2e657b83b0>

  File "aiserver.py", line 6981, in load_story_v1
    koboldai_vars.gamestarted = js["gamestarted"]
    │                           └ {'default': {'file_version': 2, 'story_name': 'test', 'lastact': "Within just a few more minutes, my whole form disappeared i...
    └ <koboldai_settings.koboldai_vars object at 0x7f2e66f20950>

KeyError: 'gamestarted'

Trying to load a local story causes this error to pop up... Maybe it is related to #171 glitch/bug?

**Comment by ebolam** [comment]
Looks like the save file might be corrupt. Look at the file for a gamestarted variable. If it's missing add it with a true value.
