### ISSUE TITLE
OSError: [Errno 26] Text file busy: '/tmp/cloudflared-linux-amd64'

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#173]
Initializing Mesh Transformer JAX, please wait...
Connecting to your Colab instance's TPU
Elapsed Time: 0:00:00  [█                                                      ]ERROR      | __main__:<module>:11836 - An error has been caught in function '<module>', process 'MainProcess' (685), thread 'MainThread' (139936854431616):
Traceback (most recent call last):

> File "aiserver.py", line 11836, in <module>
    run()
    └ <function run at 0x7f4525ab38c0>

  File "aiserver.py", line 11797, in run
    cloudflare = _run_cloudflared(port)
                 │                └ 5000
                 └ <function _run_cloudflared at 0x7f4525af0830>

  File "/usr/local/lib/python3.7/dist-packages/flask_cloudflared.py", line 74, in _run_cloudflared
    cloudflared = subprocess.Popen([executable, 'tunnel', '--url', 'http://127.0.0.1/:' + str(port), '--metrics', '127.0.0.1:8099'], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
                  │          │      │                                                        │                                             │          │               │          └ -2
                  │          │      │                                                        │                                             │          │               └ <module 'subprocess' from '/usr/lib/python3.7/subprocess.py'>
                  │          │      │                                                        │                                             │          └ -3
                  │          │      │                                                        │                                             └ <module 'subprocess' from '/usr/lib/python3.7/subprocess.py'>
                  │          │      │                                                        └ 5000
                  │          │      └ '/tmp/cloudflared-linux-amd64'
                  │          └ <class 'eventlet.green.subprocess.Popen'>
                  └ <module 'subprocess' from '/usr/lib/python3.7/subprocess.py'>

  File "/usr/local/lib/python3.7/dist-packages/eventlet/green/subprocess.py", line 58, in __init__
    subprocess_orig.Popen.__init__(self, args, 0, *argss, **kwds)
    │               │     │        │     │         │        └ {'stdout': -3, 'stderr': -2}
    │               │     │        │     │         └ ()
    │               │     │        │     └ ['/tmp/cloudflared-linux-amd64', 'tunnel', '--url', 'http://127.0.0.1:5000/', '--metrics', '127.0.0.1:8099']
    │               │     │        └ <eventlet.green.subprocess.Popen object at 0x7f4525aed850>
    │               │     └ <function Popen.__init__ at 0x7f4591e1d320>
    │               └ <class 'subprocess.Popen'>
    └ <module 'subprocess' from '/usr/lib/python3.7/subprocess.py'>

  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
    │                └ False
    └ True
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
          │                    │          │        └ '/tmp/cloudflared-linux-amd64'
          │                    │          └ 'Text file busy'
          │                    └ 26
          └ <class 'OSError'>

OSError: [Errno 26] Text file busy: '/tmp/cloudflared-linux-amd64'
Elapsed Time: 0:00:59  [                                        █              ]

This seems to pop up at random when trying to start a fresh TPU instance. Simple restart helps, weirdly enough.

**Comment by ebolam** [comment]
This is something related with the tunnel itself. Can you post this in the troubleshooting channel in discord? It's not something I can fix :(

**Comment by MrXen0morph** [comment]
> This is something related with the tunnel itself. Can you post this in the troubleshooting channel in discord? It's not something I can fix :(

Would gladly do that, but can I have an invite link to the discord channel itself? Last time I've came across one, it wasn't working properly (I was redirected to an empty discord page, somehow...).

**Comment by ebolam** [comment]
Sure:
[https://koboldai.org/discord](https://koboldai.org/discord)
