### ISSUE TITLE
AssertionError upon submiting or adding to an existing prompt.

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#175]
ERROR      | __main__:generate:5791 - Traceback (most recent call last):
  File "aiserver.py", line 5779, in generate
    genout, already_generated = tpool.execute(core_generate, txt, minimum, maximum, found_entries)
  File "/usr/local/lib/python3.7/dist-packages/eventlet/tpool.py", line 132, in execute
    six.reraise(c, e, tb)
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/eventlet/tpool.py", line 86, in tworker
    rv = meth(*args, **kwargs)
  File "aiserver.py", line 4994, in core_generate
    assert gen_in.shape[-1] + koboldai_vars.genamt <= koboldai_vars.max_length
AssertionError

No idea how to reproduce properly at this point, it simply started to happen after a short time into the story. May be related to #171 in some way.

**Comment by ebolam** [comment]
Were you by any chance adjusting settings (specifically the Output Length or Context Tokens)?

**Comment by MrXen0morph** [comment]
Pretty sure I didn't, they are all on default values (80 for output and 2048 for memory).

**Comment by ebolam** [comment]
This should be fixed now

**Comment by MrXen0morph** [comment]
The issue seems to reappear again on the older stories.
Addendum, this is also true for the completely new, fresh stories as well, after some time into the story specifically.
