### ISSUE TITLE
Blank Lines before the Download Progress Bars

### ISSUE THREAD

**Issue by LightSaveUs** [ebolam/KoboldAI#177]
Official:

Loading model tensors: 100%|████████████████████████████████████| 197/197 [00:01<00:00, 151.63it/s]

United:

INIT       | Loading model tensors: 100%|##########| 197/197 [00:01<00:00, 159.17it/s]

New UI:

/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py:624: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  FutureWarning,
-blank line-
-blank line-
-blank line-
-blank line-
-blank line-
-blank line-
-blank line-
-blank line-
-blank line-
-blank line-
-blank line-
-blank line-
-blank line-
INIT       | Loading model tensors: 100%|##########| 197/197 [00:01<00:00, 123.91it/s]

**Comment by ebolam** [comment]
Does united do the same thing? I don't see any code differences between the two other than the extra hook I have which doesn't affect prints...

**Comment by LightSaveUs** [comment]
> Does united do the same thing? I don't see any code differences between the two other than the extra hook I have which doesn't affect prints...

No, the United doesn't do it.
It's all okay there, but there are blank lines in this fork.
