### ISSUE TITLE
[Unwanted Behaviour] Adventure mode formatting applies even when adventure mode is disabled

### ISSUE THREAD

**Issue by GuiAworld** [ebolam/KoboldAI#18]
When the Adventure Mode toggle is disabled, the Adventure mode formatting ( >Your text here) should not apply.

Btw, what's the difference between the Adventure & Chat mode toggles and the Story Mode list?

**Comment by ebolam** [comment]
This has been reworked now. The toggles are gone and replaced with a simple dropdown with the three modes (story, adventure, chat). The chat mode of KoboldAI is not used in the new UI yet, but it will set the appropriate flags for the old UI.
