### ISSUE TITLE
Too Much Generations Issue

### ISSUE THREAD

**Issue by LightSaveUs** [ebolam/KoboldAI#182]
From lunarbob19.
"I'm using the Erebus20B on Collab on the new UI. I keep randomly getting this error as it finds some problem with what it just generated. So I have to delete the recent entry before it will work again."
There was actually only like a dozen total actions in that story, at about 150-200 output length each.

Error log:

ERROR      | main:generate:5825 - Traceback (most recent call last):
  File "aiserver.py", line 5813, in generate
    genout, already_generated = tpool.execute(core_generate, txt, minimum, maximum, found_entries)
  File "/usr/local/lib/python3.7/dist-packages/eventlet/tpool.py", line 132, in execute
    six.reraise(c, e, tb)
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/eventlet/tpool.py", line 86, in tworker
    rv = meth(*args, **kwargs)
  File "aiserver.py", line 5028, in core_generate
    assert gen_in.shape[-1] + koboldai_vars.genamt <= koboldai_vars.max_length
AssertionError

**Comment by one-some** [comment]
Possibly a result of new gen code. I assume this happens with a full context?

**Comment by LightSaveUs** [comment]
No idea, one-some.
You may ask lunarbob19 on Discord. He has encountered this problem and may know more.

**Comment by ebolam** [comment]
Fixed
