### ISSUE TITLE
Chat Mode: Not actually initializing

### ISSUE THREAD

**Issue by scythe000** [ebolam/KoboldAI#183]
I -finally- got chat mode working. After working with @Darth who was incredibly kind and patient, and trying so many different things, we finally figured something must be borked with my installation. I did a fresh pull from UI2 (on 2022-09-29), and still no luck. So I did a fresh clone from Henk, and BAM, al lthe same settings, but it worked perfectly out the box in chat mode. 
So I think I know what's up. I thiiiink that your branch isn't actually switching to chat mode. I think it's staying in story mode, and that's why no matter what, it would keep returning both sides of the conversation.  I tried for both NewUI and regular UI.

**Comment by one-some** [comment]
Believe this was fixed

**Comment by ebolam** [comment]
@scythe000, Do you have a story you could share (even a small one)? I'm trying to dive into this now but don't really play chat mode and want to make sure it's working the way it should be.

**Comment by ebolam** [comment]
Tried chat mode a bit and it appears to be working now other than some extra line breaks. First two lines are the prompt:
```
Joe: Hey!
You: Hey Joe, how have you been?
Joe: I've been good.

You: So did you complete that report you were working on last week?

Joe: Yeah.
You: That's good to hear.

Joe: I'm glad you're doing well.
```

**Comment by scythe000** [comment]
Awesome, I’ll test it out later. Any idea what changed?

**Comment by ebolam** [comment]
Ya. the formatting function wasn't always being run as well as a few other things.
