### ISSUE TITLE
Link to the GUI leads to an error message 404 displayed on the page.

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#251]
Basically the title, all tensors are loaded, once the 2 links show up (old UI and a new one), both of them lead to a 404 error page. (the page has literally nothing but a 404 number and a different background color).

**Comment by ebolam** [comment]
What does the URL look like? I can't seem to get a TPU this morning

**Comment by MrXen0morph** [comment]
> What does the URL look like? I can't seem to get a TPU this morning

Can't get one either, but I think I remember it looking exactly the same as in the launch window.
Is it safe to post a link here, if it isn't active anymore?
https://rich-moles-doubt-34-170-223-6.loca.lt/new_ui

**Comment by MrXen0morph** [comment]
Also the link remains the same every time I try to start it on Colab... Exactly the same as the one above, literallly.

**Comment by LightSaveUs** [comment]
Not sure, but it may be the same error I had with the one and the same links some time ago.
Though I haven't met it since then. It was fixed,

**Comment by MrXen0morph** [comment]
> Not sure, but it may be the same error I had with the one and the same links some time ago. Though I haven't met it since then. It was fixed,

No idea ^^;
All I can say that no matter when I get the completely new TPU, or use the 'old' one (after using United), trying to launch ebolam's KoboldAI, displays the link above (it was like that since yesterday)... Which still somehow leads to a 404 error, even if the TPU is no longer relevant.

**Comment by ebolam** [comment]
That helps. Might be an issue I ran into a while ago.

**Comment by ebolam** [comment]
This might be fixed now. I'll test it when I can get a TPU colab instance. If you see it working feel free to reply here, or close the issue so I know it's good.

**Comment by ebolam** [comment]
Fixed in commit 72121519dec04ff9aa24919d3e67472f8e0c2114
