### ISSUE TITLE
Weird GUI bug

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#264]
So uh... This 'happened'
![image](https://user-images.githubusercontent.com/55456465/198859617-473eb873-be08-4684-b889-e2fb86a2d296.png)

**Comment by MrXen0morph** [comment]
Addendum, whenever an edit is made to an existing line, a right-side box shows up (where previous outputs are saved) shows up, but completely empty.

**Comment by ebolam** [comment]
This should be fixed now. Please take a look and close the issue if it is.
