### ISSUE TITLE
Clicking Add to World Info Entry duplicates all World Info

### ISSUE THREAD

**Issue by ghost** [ebolam/KoboldAI#265]
Hi, not sure if that is the one that triggers it but, it happens twice now when I add to World Info when right clicking a text, it duplicates the rest of the world info and I have to delete them.

**Comment by ebolam** [comment]
Do you mean it adds two cards when using the "add to world info entry" option from right click menu?

**Comment by ghost** [comment]
Yes, It literally duplicates already existing world info,  though now I'm not sure if right click adding world info triggers it or editing the text of current world info keys. I think either one of those triggers the duplication. Is there a way to duplicate world info entries though, maybe I'm just clicking on it.

**Comment by ebolam** [comment]
I think this is fixed now. 

Let me know if you get it again. Same for the constant bug (duplicating on setting constant)
