### ISSUE TITLE
Model Welcome Text position

### ISSUE THREAD

**Issue by LightSaveUs** [ebolam/KoboldAI#272]
The welcome text is at the very top of the gamescreen when the model is loaded. I think this is a flaw and suggest that the model welcome text be placed at the bottom of the gamescreen, similar to the position of the default welcome text.

Model Welcome Text:
![1](https://user-images.githubusercontent.com/108632621/198924432-077401df-e669-441d-9df7-41fb49470571.png)

Default Welcome Text (positioned correctly):
![2](https://user-images.githubusercontent.com/108632621/198925928-74b0ea88-8d24-4db5-865b-583adcf77549.png)

**Comment by ebolam** [comment]
Fixed.
