### ISSUE TITLE
Sequence Area popping out

### ISSUE THREAD

**Issue by LightSaveUs** [ebolam/KoboldAI#273]
After you click from the highlighted chunk to outside the gamescreen, the sequence area drops out.

![3](https://user-images.githubusercontent.com/108632621/198926442-87ceff9a-a202-4536-a43b-ad014017bb22.png)

Link to the testing video:
https://drive.google.com/file/d/1ahpfh19D7tFMTKbfXGLbol0kK1fPlq4O/view?usp=sharing

Link to the story used in the test:
https://drive.google.com/file/d/1FLdw0yjfoKImVOp0i54V8MkI5_KgMITy/view?usp=sharing

**Comment by ebolam** [comment]
This is likely fixed now. We had some editing bugs that likely caused this error.
