### ISSUE TITLE
Dublicating World Info on 'always include' active.

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#282]
Basically the title. Every time an option to 'always include' is activated, the WI is dublicated. (Oddly enough, the newly created dublicate has the option 'always include' ticked off).

Is this intentional, or is it a bug?

**Comment by LightSaveUs** [comment]
I think it was fixed.
I caught this bug in the past, but it was okay on my side after ebo squashed it.

**Comment by MrXen0morph** [comment]
Odd, because the glitch was still there an hour or two ago.

**Comment by ebolam** [comment]
Merged with issue 265 (https://github.com/ebolam/KoboldAI/issues/265)
