### ISSUE TITLE
Loading json file from local to colab only loads the prompt, etc. but not the story itself

### ISSUE THREAD

**Issue by ghost** [ebolam/KoboldAI#285]
Loading json file from local to colab only loads the prompt, memory, etc., but not the rest of the story. Not sure if it's only on colab though.

**Comment by ebolam** [comment]
Haven't seen that before. Are there any errors in the console (javascript or colab console)?

**Comment by ghost** [comment]
[Error.txt](https://github.com/ebolam/KoboldAI/files/9942766/Error.txt) Yes it looks like there is an error in the console. I attached it here.

**Comment by ebolam** [comment]
Potential Fix 5ea921d17e7a1877c80db334dd43a814cc895ebf

Let me know if it still does it and we can re-open the issue

**Comment by ghost** [comment]
Good day,

It now loads the story but now I get "No prompt or random story theme entered." Pop up and a bunch of errors I'll attach here (not sure if the error messages are repeating since I click on generate a couple of times.) Also seems like a huge chunk of the story is not in bold letters and probably off format, and the last parts are in bold letters (which I assume is the default format I have.) And should this be a new issue?

[Error.txt](https://github.com/ebolam/KoboldAI/files/9977108/Error.txt)

![NO Prompt](https://user-images.githubusercontent.com/113113106/200994031-5b784919-fdec-4fef-8f54-c1a44cde7281.PNG)

**Comment by ebolam** [comment]
I see the issue now. Somehow the world info list added a entry with an ID of -1 which shouldn't be possible. That's reserved for new world info before it's transmitted to the backend and from there it gets assigned a new ID. It's also missing one of the fields probably because it wasn't added through the normal process. Was the card titled "New World Info Entry" created by hand or the right click add to WI method?

**Comment by ghost** [comment]
Hi it was a previous save with v1 that I imported from aetheroom and that I continued with V2 with no issues. Most of the WI was added on V1, while the last 3 I think was added via right click. I also then saved a local json copy of the file then loaded it with the first issue that only the prompt is loaded then now the latest error showing "no prompt or random story theme entered."

**Comment by ebolam** [comment]
This appears to be limited to a bad save file now. Let me know if you get it again on a new save (or a v1 save)
