### ISSUE TITLE
Using delete save button on Colab doesn't delete the file itself on gdrive, even if its name is already deleted in the UI

### ISSUE THREAD

**Issue by ghost** [ebolam/KoboldAI#286]
Using delete save button on Colab doesn't delete the file itself on gdrive, even if its name is already deleted in the UI. Tried importing a story from local to colab, says it already has a name, tried deleting the file with the same name, it still exists in Gdrive and I have to delete it manually there.

**Comment by ebolam** [comment]
It does seem to delete files correctly now (I don't think anything changed). There is a lag though between the KoboldAI delete and it actually disappearing from google drive, as much as a minute or two, but I was able to delete half a dozen stories from my drive by deleting them using the load story dialog.
