### ISSUE TITLE
Action Count is broken

### ISSUE THREAD

**Issue by LightSaveUs** [ebolam/KoboldAI#287]
In the load story popup the number of actions for stories is displayed incorrectly. Often with a value of 0. Also, the number of actions in the new and old UI are different, indicating that this problem exists.

New UI:
![image](https://user-images.githubusercontent.com/108632621/200053025-b7107bd1-1936-4c05-84cf-74dd8e4a0a46.png)

Old UI:
![image](https://user-images.githubusercontent.com/108632621/200053403-f45f011b-9f60-4177-8005-3cce754e3594.png)

**Comment by ebolam** [comment]
Fixed in 52b6d26977dd9ddacf4c8e34ec76572cf8302f81
