### ISSUE TITLE
Too many spaces at the end of each sentence.

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#291]
Basically the title. Here's the extra options that I have active, and that might affect the output.
![image](https://user-images.githubusercontent.com/55456465/200990862-12f3dbbd-7daa-4e0b-8256-62c867e7e2c2.png)

**Comment by ebolam** [comment]
Can you check the context viewer to see if the spaces are only visual or actually in the text? The context viewer can be shown by clicking on the bar at the bottom of the right flyout. All AI text will be colored with small black spaces separating each sentence (but that's just to see the different sentences easier). Are there any double spaces that are colored?

**Comment by MrXen0morph** [comment]
> 

Yes, there are separate tokens with just empty spaces in them. Also it seems like the moment you stop controlling those spaces (edit out too many), they begin to multiply way too much. xD

**Comment by MrXen0morph** [comment]
It also likes to put an empty output into the text, as a separate action if you hit Submit, which consist only of 2 spaces. lol

**Comment by ebolam** [comment]
Likely fixed in  4b54b970804039466660fa58f34987542f48555f. If the spaces were split across actions it would not trim. It now will.
