### ISSUE TITLE
World Info Duplicates Again

### ISSUE THREAD

**Issue by ghost** [ebolam/KoboldAI#295]
Hi there, now I'm not sure what doubles the World Info entries as I'm not doing any right click add world info and it still duplicates. I also had some errors and I'm not really sure if its connected with this problem but I will upload it nonetheless.
[error.txt](https://github.com/ebolam/KoboldAI/files/9994730/error.txt)

**Comment by one-some** [comment]
I can reproduce this by saving, creating a new story, and loading

**Comment by ghost** [comment]
Probably that it is the reason. I've done those things usually.

**Comment by MrXen0morph** [comment]
The bug manifest itself on loading a story, once you load it (doesn't matter if new or not, as long as it is saved, it will be enough).
Once you load, you have dublication already in place.

**Comment by ghost** [comment]
Also, I'm not sure if its connected here but that story also has the generation above the prompt.

**Comment by MrXen0morph** [comment]
> Also, I'm not sure if its connected here but that story also has the generation above the prompt.

Create a new issue for this. As far as I can tell, this isn't related to the WI in any way. 
Also yes, I had this problem before as well, can't cause it to pop up anymore.

**Comment by ghost** [comment]
@ebolam Apparently my WI still duplicates for me, I think it involves saving and loading or pressing undo a couple of times or changing UI mode. Those were the only things I did I believe.

Edit: I think just loading a file triggers it.
