### ISSUE TITLE
Error: connection refused

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#296]
/tools/node/lib/node_modules/localtunnel/bin/lt.js:81
    throw err;
    ^

Error: connection refused: localtunnel.me:38633 (check your firewall settings)
    at Socket.<anonymous> (/tools/node/lib/node_modules/localtunnel/lib/TunnelCluster.js:52:11)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    

I honestly have no idea why and what happened here... I was just trying to create a new prompt for a new story, and then this popped up in the console, cutting off the connection. I should mention that I was using it for 5~ hours without any issues. Is changing PC can be a problem? At least it wasn't before...

**Comment by ebolam** [comment]
Difficult to see what's going on. It lost communication with the backend, which would generally be a crash of some kind.... Was there any errors in the python console?

**Comment by MrXen0morph** [comment]
This happened on Colab version, therefore I can't provide anything but this... Also it happened again yesterday.

Unless there is an extra log dump Im not aware about lol.

**Comment by ebolam** [comment]
It might be the localtunnel crashing/disconnecting based on that error.

**Comment by ebolam** [comment]
Closing as it hasn't happened again that I'm aware of. Appears to be a localtunnel issue
