### ISSUE TITLE
Story Generation Appears above the Prompt

### ISSUE THREAD

**Issue by ghost** [ebolam/KoboldAI#300]
Hi, I got this randomly before, one time when there was a problem when clicking undo not deleting the story, but the latest seems to be connected to my save that has duplication of World Info.

**Comment by ebolam** [comment]
Any idea how to duplicate the result? I imagine a browser refresh fixed it...

**Comment by ghost** [comment]
Really am not sure how, last time it repeats after loading the story then there was an undo bug it somehow got fixed during that time. The latest one, seems like I loaded the file again then its fine.

**Comment by ghost** [comment]
HI @ebolam, currently it looks like the problem occurs once we press actions very fast like the undo action and it gets fixed by just refreshing the page. I think the case can be closed for now if that only is the reason and refreshing could fix it, but if something can be done to prevent that in the first place then I'm all ears. Thanks.
