### ISSUE TITLE
Chatmode stopper padding has turned evil and acts in an unorthodox manner which is not expected

### ISSUE THREAD

**Issue by one-some** [ebolam/KoboldAI#302]
The chatmode stopper seems to randomly fire and place 6 or 7 null tokens (regardless of name length)
see discussions [here](https://discord.com/channels/849937185893384223/988323759184293948/1043351565437767700) and [here](https://discord.com/channels/849937185893384223/988323759184293948/1043634545343344650)

**Comment by ebolam** [comment]
Possible fix in
