### ISSUE TITLE
Adjust text size option missing

### ISSUE THREAD

**Issue by ghost** [ebolam/KoboldAI#311]
Hi there, I think the way to adjust the text size is missing, is this intentional? Shouldn't it be here?
![SA](https://user-images.githubusercontent.com/113113106/204069787-3b43e69d-922a-4a11-b0ca-4a8f71057d86.png)

**Comment by ebolam** [comment]
Fixed in d3abf1761898e38838be29088c04f7943d5ed437

**Comment by ghost** [comment]
@ebolam How about Max game screen size, etc. forgot the others.
