### ISSUE TITLE
Loading introduces WI Duplication?

### ISSUE THREAD

**Issue by ghost** [ebolam/KoboldAI#315]
Still having this issue and maybe it's loading this time?

**Comment by ebolam** [comment]
I tried loading my WI test story in chrome. It loaded OK. I then loaded it again, same output. I create a new story, then loaded my WI test story again, still no issues.

Can you give an exact steps to reproduce from a new KoboldAI instance?

**Comment by one-some** [comment]
> I tried loading my WI test story in chrome. It loaded OK. I then loaded it again, same output. I create a new story, then loaded my WI test story again, still no issues.
> 
> Can you give an exact steps to reproduce from a new KoboldAI instance?

This can be reproduced by making a new story, making a new WI entry, saving, and then loading

**Comment by one-some** [comment]
fixed by a8f8129c976a428cf7cdfc91a26db06b57d864d6

**Comment by ghost** [comment]
Hi seems like I have a new issue regarding duplication. Seems like loading two saves consecutively copies the WI of the first loaded save to the other. Workaround involves making a blank story and loading another save.

**Comment by ebolam** [comment]
Fix in a27651ef1b2af378d50337a7486d4e6dc04ffc9e
