### ISSUE TITLE
Triple clicking on the prompt throws an error

### ISSUE THREAD

**Issue by one-some** [ebolam/KoboldAI#317]
`koboldai.js:2902: TypeError: selected_game_chunk is null`
As of reporting this, that line is
`selected_game_chunk.classList.add("editing");` in `edit_game_text();`

**Comment by ebolam** [comment]
This may not be fixable... On triple click the browser is giving the selected text area as the selected object, meaning we don't really know what's been selected...

**Comment by ebolam** [comment]
074ec612eb48cc4bf7fc3004b3aa9f9a9a99dfa1
