### ISSUE TITLE
Repeatedly pressing Ctrl+Left Arrow while editing the prompt throws an error

### ISSUE THREAD

**Issue by one-some** [ebolam/KoboldAI#318]
`koboldai.js:2870: TypeError: window.getSelection().anchorNode is null`
Currently, this points to `if(window.getSelection().anchorNode.parentNode) {` in `select_game_text()`

Reproduction steps:
1. Load a story
2. Reload the page (needed sometimes?)
3. Click on some place in the beginningish of the prompt to edit it
4. Keep pressing Ctrl+Left Arrow to go to the previous word
5. When the beginning is reached, the error should appear

**Comment by ebolam** [comment]
Fixed in 0371fa1782f577b081cb7b31a4d45b1b8b5c1276
