### ISSUE TITLE
An error has been caught in function 'g', process 'MainProcess' (710), thread 'MainThread' 

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#341]
ERROR      | __main__:g:589 - An error has been caught in function 'g', process 'MainProcess' (710), thread 'MainThread' (140019659818880):
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/thread.py", line 43, in __thread_body
    func(*args, **kwargs)
    │     │       └ {}
    │     └ ()
    └ <bound method Thread._bootstrap of <Thread(Thread-311, started daemon 140015713734080)>>

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function start_new_thread.<locals>.wrap_bootstrap_inner at 0x7f57f2cff820>
    └ <Thread(Thread-311, started daemon 140015713734080)>

  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/thread.py", line 64, in wrap_bootstrap_inner
    bootstrap_inner()
    └ <bound method Thread._bootstrap_inner of <Thread(Thread-311, started daemon 140015713734080)>>

  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f58d980e8b0>
    └ <Thread(Thread-311, started daemon 140015713734080)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-311, started daemon 140015713734080)>
    │    │        │    └ (<socketio.server.Server object at 0x7f581bfbcc40>, 'm4LOEm6QmT6WcubIAAAB', 'sqgzn0pOMpej72SLAAAA', ['submit', {'data': 'As I...
    │    │        └ <Thread(Thread-311, started daemon 140015713734080)>
    │    └ <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7f581bfbcc40>>
    └ <Thread(Thread-311, started daemon 140015713734080)>

  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 731, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
        │      │              │        │          │     └ ['submit', {'data': 'As I walk through the thick vegetation of  the jungles, I accidentally come across Mewra, the anthropomo...
        │      │              │        │          └ 'm4LOEm6QmT6WcubIAAAB'
        │      │              │        └ '/'
        │      │              └ ['submit', {'data': 'As I walk through the thick vegetation of  the jungles, I accidentally come across Mewra, the anthropomo...
        │      └ <function Server._trigger_event at 0x7f581c68d040>
        └ <socketio.server.Server object at 0x7f581bfbcc40>

  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 756, in _trigger_event
    return self.handlers[namespace][event](*args)
           │    │        │          │       └ ('m4LOEm6QmT6WcubIAAAB', {'data': 'As I walk through the thick vegetation of  the jungles, I accidentally come across Mewra, ...
           │    │        │          └ 'submit'
           │    │        └ '/'
           │    └ {'/': {'OAI_Key_Update': <function get_oai_models at 0x7f581912bf70>, 'get_cluster_models': <function get_cluster_models at 0...
           └ <socketio.server.Server object at 0x7f581bfbcc40>

  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
           │    │             │        │        │          └ 'm4LOEm6QmT6WcubIAAAB'
           │    │             │        │        └ '/'
           │    │             │        └ 'submit'
           │    │             └ <function UI_2_submit at 0x7f58190fa040>
           │    └ <function SocketIO._handle_event at 0x7f581c100670>
           └ <flask_socketio.SocketIO object at 0x7f581c027d30>

  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 828, in _handle_event
    ret = handler(*args)
          │        └ ({'data': 'As I walk through the thick vegetation of  the jungles, I accidentally come across Mewra, the anthropomorphic pant...
          └ <function UI_2_submit at 0x7f58190fa040>

> File "aiserver.py", line 589, in g
    return f(*a, **k)
           │  │    └ {}
           │  └ ({'data': 'As I walk through the thick vegetation of  the jungles, I accidentally come across Mewra, the anthropomorphic pant...
           └ <function UI_2_submit at 0x7f5819105d30>

  File "aiserver.py", line 8672, in UI_2_submit
    actionsubmit(data['data'], actionmode=koboldai_vars.actionmode)
    │            │                        └ <koboldai_settings.koboldai_vars object at 0x7f581bf351c0>
    │            └ {'data': 'As I walk through the thick vegetation of  the jungles, I accidentally come across Mewra, the anthropomorphic panth...
    └ <function actionsubmit at 0x7f581913a820>

  File "aiserver.py", line 4839, in actionsubmit
    calcsubmit("") # Run the first action through the generator
    └ <function calcsubmit at 0x7f581913adc0>

  File "aiserver.py", line 5308, in calcsubmit
    generate(subtxt, min, max, found_entries)
    │        │       │    │    └ {0}
    │        │       │    └ 419
    │        │       └ 299
    │        └ [46, 999, 376, 310, 247, 5343, 21698, 13468, 20018, 379, 13, 342, 2240, 32805, 290, 13, 49625, 3753, 13, 533, 342, 247, 2257,...
    └ <function generate at 0x7f5819142790>

  File "aiserver.py", line 6263, in generate
    koboldai_vars.lua_koboldbridge.generated[i+1][koboldai_vars.generated_tkns] = int(genout[i, -1].item())
    │                                        │    │                                   │      └ 0
    │                                        │    │                                   └ [[26133, 1680, 3253, 4030, 865]]
    │                                        │    └ <koboldai_settings.koboldai_vars object at 0x7f581bf351c0>
    │                                        └ 0
    └ <koboldai_settings.koboldai_vars object at 0x7f581bf351c0>

TypeError: list indices must be integers or slices, not tuple

Oof.

**Comment by ebolam** [comment]
This is some kind of lua error. What settings did you have? Dynamic world info? Alt multi-gen? User Scripts enabled?

**Comment by tomsy127** [comment]
Almost same for me.
I have initialized the environment and tested.
Here are my steps and error log.
![pal1](https://user-images.githubusercontent.com/95439328/208226717-3c1a3448-237a-453b-bc70-3d13f3c69412.jpg)
![pal2](https://user-images.githubusercontent.com/95439328/208226719-3f420260-c610-493d-9681-1caaebf239c6.jpg)
![pal3](https://user-images.githubusercontent.com/95439328/208226720-c5c0edbb-02c8-421f-8b47-ba02d10f12b5.jpg)
![pal4](https://user-images.githubusercontent.com/95439328/208226727-5b43bb7c-1e97-45d7-8eab-64cae93dbdaf.jpg)
![pal5](https://user-images.githubusercontent.com/95439328/208226731-bbdd3dbe-3c0c-445d-b0d4-5508c50de492.jpg)
![pal6](https://user-images.githubusercontent.com/95439328/208227585-d555fd71-09e3-4d06-b057-be4442a16450.jpg)

**Comment by MrXen0morph** [comment]
> This is some kind of lua error. What settings did you have? Dynamic world info? Alt multi-gen? User Scripts enabled?

I had pretty much everything on default, none of the things you've mentioned. The only thing different was the adventure mode switched to Chat, as I decided to test it. Changing back didn't fix the issue by the way.

**Comment by one-some** [comment]
Should be fixed by #349
