### ISSUE TITLE
omegaconf dependency missing for new TTS feature after fresh install, additional error

### ISSUE THREAD

**Issue by madcatandrew** [ebolam/KoboldAI#355]
Looks like the omegaconf dependency is not included for silero_tts after running install_requirements. Tried running Update and retried install again later.

Also simply enabling Generate Audio throws this error in the sync_to_server function:

```
Error at koboldai.js:2915
Uncaught TypeError: Cannot use 'in' operator to search for 'status' in undefined
```

**Comment by ebolam** [comment]
Fixed
