### ISSUE TITLE
Softprompts not working with new UI

### ISSUE THREAD

**Issue by See-Ya-space-cowboy** [ebolam/KoboldAI#360]
So if I try to use a softprompt on the new UI version I get an Error. I think this is the Error is below.

"TypeError: sequence item 0: expected str instance, NoneType found"

I ran into this on Nerys 13B V2. I also get the same problem with some of the 6B models.

it doesn't seem to happen with random generations, just happens when you write a new line manually.

**Comment by ebolam** [comment]
Fixed now. Pull request is in for United
