### ISSUE TITLE
"tortoise" SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#361]
Launching KoboldAI with the following options : python3 aiserver.py --model KoboldAI/GPT-NeoX-20B-Erebus --localtunnel --colab
Traceback (most recent call last):
  File "aiserver.py", line 73, in <module>
    import koboldai_settings
  File "/content/KoboldAI-Client/koboldai_settings.py", line 2053
    if self.tortoise is None and importlib.util.find_spec("tortoise") is not None::
                                                                                  ^
SyntaxError: invalid syntax

Simply started a fresh TPU.

**Comment by ebolam** [comment]
This is fixed now. Had a double :: at the end...
