### ISSUE TITLE
Sequence area closing problem

### ISSUE THREAD

**Issue by LightSaveUs** [ebolam/KoboldAI#43]
Sequence area is not closed, no matter if there are multiple gens, or not. It appears by default after first load.
Ideally, it should be absent at one gen and open and close if there are multiple gens.
![image](https://user-images.githubusercontent.com/108632621/185677587-57a113c8-1e7f-4576-a765-f583e4f8cff5.png)

**Comment by ebolam** [comment]
Not really fixable :( It does go away when text is loaded.
