### ISSUE TITLE
WI Card Disappears when dragged into a invalid place

### ISSUE THREAD

**Issue by GuiAworld** [ebolam/KoboldAI#51]
Also, WI Cards can be dragged inside the text box input
https://user-images.githubusercontent.com/71558823/186268749-7a052b4f-78f5-49eb-ab55-11d2484a7cbd.mp4

**Comment by GuiAworld** [comment]
Just adding a new information. it is possible to drag a WI Card into the text area

**Comment by ebolam** [comment]
Ugh, that's a nasty bug....
Guess I'll need to do more reading on drag/drop mechanics.

**Comment by ebolam** [comment]
Fixed. On Fire Fox it will still add random text when you drag it on top of text editable elements... Not much of a way to fix that from what I can tell
