### ISSUE TITLE
Some palette colours are not displaying properly

### ISSUE THREAD

**Issue by GuiAworld** [ebolam/KoboldAI#52]
Using Chrome
![image](https://user-images.githubusercontent.com/71558823/186269025-9c620b6d-b0fd-476e-a7d6-93abd0aca302.png)

**Comment by GuiAworld** [comment]
Well...
![image](https://user-images.githubusercontent.com/71558823/186550404-d6a62f41-cc73-4a2c-8a85-570944216fab.png)

**Comment by ebolam** [comment]
![image](https://user-images.githubusercontent.com/7979032/186729694-410d5bf2-5454-4264-a7ae-5482254fc733.png)
