### ISSUE TITLE
World Info and Author's Note are empty (Colab problem)

### ISSUE THREAD

**Issue by LightSaveUs** [ebolam/KoboldAI#68]
**Only occurs in the Colab version! There is no such problem in the local version.**

Kobold does not see/erase World Info and Author's Note in the stories (and even in the story json files themselves) in both the new and old interface. When running the official version, there is no such problem and all WIs and ANs are displayed correctly.

one-some's opinion:

we basically get the data out of the save file bit by bit, eg first we do story, then we do authors note, etc
theres some error that occurs at the beginning of that area of code due to some save reading issue
the error causes the rest of the function to be aborted, so the authors note and wi is not loaded

How to cause it:

1. Create a story in the old ui (in the official version)
2. Fill the World Info and Author's Note with some information
3. Save the story
4. Load the story using this fork
5. World Info and Author's Note are empty, and even absent in the json files

Error log:

> loading /content/KoboldAI-Client/stories/At The Mercy of My Aunt.json
> Exception in thread Thread-11:
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.7/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 730, in _handle_event_internal
>     r = server._trigger_event(data[0], namespace, sid, *data[1:])
>   File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 755, in _trigger_event
>     return self.handlers[namespace][event](*args)
>   File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 283, in _handler
>     *args)
>   File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 826, in _handle_event
>     ret = handler(*args)
>   File "aiserver.py", line 271, in g
>     return f(*a, **k)
>   File "aiserver.py", line 7198, in UI_2_load_story
>     loadRequest(file)
>   File "aiserver.py", line 6099, in loadRequest
>     loadJSON(js)
>   File "aiserver.py", line 6112, in loadJSON
>     load_story_v1(json_data)
>   File "aiserver.py", line 6168, in load_story_v1
>     data["text"] = data.pop("Text")
> TypeError: 'str' object cannot be interpreted as an integer

**Comment by one-some** [comment]
this is caused by `js["actions_metadata"][key]["Alternative Text"]` being a list when it should be a dictionary, at `aiserver.py:6167`. the exception is swallowed by the server, but we should probably abort loading and notify the user instead of silently aborting midway through, in case future bugs like this happen
