### ISSUE TITLE
Vars cleanup

### ISSUE THREAD

**Issue by LightSaveUs** [ebolam/KoboldAI#95]
At the moment, the vars sheet that is available in the new interface has some shortcomings. Among them:

Missing vars for:

- ~~Error popup window (background, text color, title bar background color, title bar text color)~~
- Token bar color (background color, border color) (can be tied to --setting_footer vars, so as it's a footer too)
- Load Story Popup window (internal text color (Story Name, Action Count, Drag file(s)...))
- Advanced Theme Editor Popup window (ok button text color and background color, internal text color (vars names text color))
- Import a Story window ("Accept" and "Cancel" buttons (text color, background color))

~~Nonfunctional vars:~~

~~--tooltip_text (does not change anything, because tooltips are now a default browser text line, not a part of the interface that can be changed with CSS)~~
~~--tooltip_background (does not change anything, because tooltips are now a default browser text line, not a part of the interface that can be changed with CSS)~~
~~--wi_card_border_color_to_ai (I haven't seen anything change from changing the color of this var)~~
~~--radius_buttons (nothing changes from increasing/decreasing the value)~~

Missing rounding vars for:

- Tabs
- ~~Load Model and Story (including Import a Story) Buttons~~
- ~~Submit and Undo/Retry/Redo Buttons~~
- ~~Advanced Theme and Add World Info Entry Buttons~~

~~Problematic vars:~~

~~--error_palette, --on_error_palette, --error_container_palette, --on_error_container_palette (due to the lack of appropriate vars in the advanced theme section they cannot be deactivated (#000000) if the theme does not support or partially supports the palette system)~~
~~--layer1_palette (affects the flyout menu background color and the sequence area background color, which also makes it impossible to deactivate (#000000) if the theme does not support or partially supports the palette system)~~

Missing vars to be added ~~nonfunctional vars to be deleted/fixed and problematic vars to be fixed~~

**Comment by GuiAworld** [comment]
About the Error vars~~It's best to move them to Advanced Theme, and remove it from the palette table, and switch it to the background vars.

I'll be working on the new vars alogside some tweaks for the UI in general
--layer1_palette should be fixed since the var splitting, maybe I erased the fix without noticing

**Comment by ebolam** [comment]
Token bar color:
        part of settings_footer now

Story popup:
	background-color: var(--popup_item_color);
	color: var(--popup_item_color_text);

Import a Story window:
	color: var(--popup_cancel_button_color_text);
	border-color: var(--popup_cancel_button_color_text);
	background-color: var(--popup_cancel_button_color);

Advanced Theme Editor Popup window:
	color: var(--popup_item_color_text);
	background-color: var(--popup_background_color);
	
All Popup Load/OK/Cancel Buttons{
	color: var(--popup_cancel_button_color_text);
	border-color: var(--popup_cancel_button_color_text);
	background-color: var(--popup_cancel_button_color);
