### ISSUE TITLE
Palette UI changes

### ISSUE THREAD

**Issue by GuiAworld** [ebolam/KoboldAI#98]
Enlisting your help with the Palette UI

- Remove the ERROR Variables from the table
- Add the Background colours on the table, with the header Background, and 5 columns named
         - Base
         - Layer 1
         - Layer 2
         - Layer 3
         - Layer 4
- Hide the input when value is #000000

**Comment by GuiAworld** [comment]
![image](https://user-images.githubusercontent.com/71558823/188221947-01d1fce5-1697-4a57-9456-7c7bcf501273.png)

**Comment by ebolam** [comment]
Would this be a new table under the existing one?

**Comment by GuiAworld** [comment]
yes! it would be a extention of the existing table

**Comment by ebolam** [comment]
What are the vars names we're linking?

**Comment by GuiAworld** [comment]
![image](https://user-images.githubusercontent.com/71558823/188886860-2bbc43e8-ff72-4dcb-86c3-043d32d38b2f.png)
